# Generated by Django 2.2.1 on 2019-09-06 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AnimalType', models.CharField(choices=[('sow', 'Sow'), ('cow', 'Cow'), ('sheep', 'Sheep')], default='sow', max_length=255)),
                ('TagNumber', models.CharField(max_length=255)),
                ('disease', models.CharField(choices=[('diarrhea', 'DIARRHEA'), ('bedsore', 'BEDSORE')], default='diarrhea', max_length=255)),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('TreatmentStatus', models.CharField(choices=[('ok', 'Ok'), ('warning', 'Warning'), ('warning', 'Warning'), ('critical', 'Critical')], default='sow', max_length=255)),
                ('Location', models.CharField(default='Optional to set location', max_length=255)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
